### ISSUE TITLE
关于训练的问题

### ISSUE THREAD

**Issue by the90010** [YZCU/SSTtrack#5]
Traceback (most recent call last):
  File "/nvme2/user12/PycharmProjects/SSTtrack-master/lib/train/run_training.py", line 95, in <module>
    main()
  File "/nvme2/user12/PycharmProjects/SSTtrack-master/lib/train/run_training.py", line 87, in main
    run_training(args.script, args.config, cudnn_benchmark=args.cudnn_benchmark,
  File "/nvme2/user12/PycharmProjects/SSTtrack-master/lib/train/run_training.py", line 62, in run_training
    expr_func(settings)
  File "/nvme2/user12/PycharmProjects/SSTtrack-master/lib/train/train_script.py", line 32, in run
    loader_train, loader_val = build_dataloaders(cfg, settings)
  File "/nvme2/user12/PycharmProjects/SSTtrack-master/lib/train/base_functions.py", line 126, in build_dataloaders
    datasets=names2datasets(cfg.DATA.TRAIN.DATASETS_NAME, settings, opencv_loader),
  File "/nvme2/user12/PycharmProjects/SSTtrack-master/lib/train/base_functions.py", line 30, in names2datasets
    assert name in ["hsi_train", "hsi_val"]
AssertionError
作者您好！请问用HOTC数据集训练时，local的训练集路径该在哪里设置呢？我没有找到hsi相关路径设置的地方。此外，能麻烦您提供一下训练集的文件夹路径格式吗？谢谢！

**Comment by the90010** [comment]
https://github.com/botaoye/OSTrack/issues/61 已解决
